linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - shadow

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
    ignore: fmt:.*,write,Close

  govet:
    check-shadowing: true

  staticcheck:
    go: "1.21"

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  go: "1.21"
  deadline: 5m
  tests: false
  skip-files: []
  skip-dirs: []
