before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.Version={{.Version}}
    binary: tf-state-move

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - Merge pull request
      - Merge branch

brews:
  - name: tf-state-move
    repository:
      owner: DevHatRo
      name: homebrew-tap
    homepage: "https://github.com/DevHatRo/tf-state-move"
    description: "A tool to move resources between Terraform state files"
    license: "MIT"
    test: |
      system "#{bin}/tf-state-move --version"
    install: |
      bin.install "tf-state-move"
